default_language_version:
    python: python3.9.12
fail_fast: false
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.6.0
    hooks:
      - id: nbstripout
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        entry: black -l 79
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit
      entry: bandit -x tests
  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-annotations
          - flake8-blind-except
          - flake8-bugbear
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy