name: whale
dependencies:
  - python=3.9.12
  - black=22.6.0
  - flake8=4.0.1
  - jupyterlab
  - pre-commit=2.20.0
  - pytest=7.1.2
  - rope
  - pip
  - pip:
    - bandit==1.7.4
    - mypy==0.960
    - flake8-annotations==2.9.1
    - flake8-blind-except==0.2.1
    - flake8-bugbear==22.9.11
    - nbstripout==0.6.0
    - -r requirements.txt
    - .