name: ci-pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  pipeline:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: create virtual environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        channels: conda-forge,defaults
        auto-activate-base: false
        activate-environment: whale
        environment-file: environment.yml
    - name: install-whale
      run: |        
        pip install --editable .
    - name: nbstripout
      run:
        nbstripout $(find . -name "*.ipynb")
    - name: black
      run:
        black .
    - name: bandit
      run:
        bandit .
    - name: flake8
      run:
        flake8 --statistics .
    - name: run pytest
      run:
        pytest